### PR TITLE
New version of the final report, 10 May 2024

### PR DESCRIPTION
**Pull request by llemeurfr**

### CODE REVIEW

**Comment by dontcallmedom** [comment]
* can you submit the generated HTML document rather than the source ReSpec document?
* the "this version" url in the document doesn't match the naming of the file in the pull request
* the latest published version url doesn't exist

**Comment by llemeurfr** [comment]
Hi Dominique, 

I forgot that the index must be the target html file, not the ReSpec doc. Done using the command line respec tool. 

Note: I deleted manually 
```
      <dt>Latest published version:</dt><dd>
              <a href="https://www.w3.org/community/reports/tdmrep/tdmrep/">https://www.w3.org/community/reports/tdmrep/tdmrep/</a>
            </dd>
      <dt>Latest editor's draft:</dt><dd><a href="https://w3c.github.io/tdm-reservation-protocol/">https://w3c.github.io/tdm-reservation-protocol/</a></dd>
````
from the target file; I don't find their source in the ReSpec document. Seems to be generated by ReSpec. I didn't see a flag in the ReSpec doc relative to that aspect. 

> the "this version" url in the document doesn't match the naming of the file in the pull request

I don't see that. the file in the PR is tdmrep/CG-FINAL-tdmrep-20240510/index.html and the url is "https://www.w3.org/community/reports/tdmrep/CG-FINAL-tdmrep-20240510": seems to 100% match.

**Comment by llemeurfr** [comment]
Thanks a lot. 
It is now possible to change the redirection from what we consider as a stable URL for the spec =  https://www.w3.org/2022/tdmrep/ to the latest version of the spec = https://w3c.github.io/cg-reports/tdmrep/CG-FINAL-tdmrep-20240510/ ?

**Comment by dontcallmedom** [comment]
done @llemeurfr

**Pull request merged**
