### PR TITLE
Publish accessibility vocabulary and crosswalk

### PR DESCRIPTION
**Pull request by mattgarrish**
The vocabulary has added new terms for hazards and i18n features.

Formally publishing the crosswalk for the first time.

/cc @clapierre @madeleinerothberg

### CODE REVIEW

**Comment by mattgarrish** [comment]
I just noticed the publication dates are off. I'll push an update in a minute.

**Comment by mattgarrish** [comment]
Any chance these will be republished soon? We have people waiting on the i18n terms becoming official.

**Comment by dontcallmedom** [comment]
sorry about the delay, I was unavailable the past 2 weeks; I'll try to make sure there is a better backup story in such situations.

**Comment by mattgarrish** [comment]
Thanks, and no worries! I kind of figured with summer there might be a wait.

**Pull request merged**
