### PR TITLE
Publish version 0.1 of the specs from the reconciliation CG

### PR DESCRIPTION
**Pull request by wetneb**
Hello!
Our community group (Entity Reconciliation CG) would like to publish two final reports and here is the first one of them.
It is generated from https://reconciliation-api.github.io/specs/0.1/.
I hope I got the procedure right, apologies in advance if not.

### CODE REVIEW

**Comment by dontcallmedom** [comment]
Could you use an updated version of ReSpec (you're using a [copy of 24.3](https://github.com/reconciliation-api/specs/blob/master/libs/respec-w3c.js), when the latest is 32.7), or align the output with the latest template? In particular, the report shouldn't have the W3C logo to avoid possible confusion with W3C Technical Reports.

also, you speak of two final reports coming - will the naming scheme you're using here (`CG-FINAL-specs-0.1-20230316` accommodate this second report? In other words, will the other report use `specs-0.2` as a shortname? (this is entirely up to your group for sake of clarity - this is mostly to ensure this isn't creating issue for you down the line)

**Comment by wetneb** [comment]
Yes we will use `specs-0.2` as shortname for the other one.

I will work on updating respec or the template.

**Comment by dontcallmedom** [comment]
thanks for the update, this looks good to me; can you confirm this is ready to publish from your perspective as well?

**Comment by wetneb** [comment]
Yes! I am a bit surprised that with the new template there is an empty space where the W3C CG logo used to be, but if that's intended with the new design, then it's all good on my side.

**Comment by dontcallmedom** [comment]
ah, well spotted, indeed the CG logo doesn't show up when the browser window is wide enough, which I think is because you have the abstract and status sections within a top level `<section id='reconciliation-service-api'>` element, when they would be expected to live on their own (and impacts the layout of the table of content over the CG logo) - would you mind fixing this?

**Comment by wetneb** [comment]
Ah thanks, it looks like the problem was our inclusion of an `<h1>` before the abstract. I have removed it and it seems to have solved the problem.

**Pull request merged**
