### PR TITLE
DPVCG 2.0 reports

### PR DESCRIPTION
**Pull request by coolharsh55**
- dpv
- pd
- tech
- loc
- risk
- ai
- justifications
- legal (de, eu, gb, ie, in, us)
- legal-eu gdpr, aiact, nis2, dga
- examples
- primer

### CODE REVIEW

**Comment by dontcallmedom** [comment]
hi @coolharsh55 - a number of the reports have mismatches between their "this version" link and the URLs that will be generated by this pull request, due to date mismatches: `ai`, `examples`, `primer`.

For some reason, in a wide browser window, the CG Final Report logo doesn't show up - it gets hidden by the navigation bar, which doesn't happen in other reports; do you know why that may be the case?

**Comment by coolharsh55** [comment]
Hi @dontcallmedom - I'll check and fix the links. Sorry about that. For the logo - I don't know, I'll try to see what's going on. It could be the image CSS we have for figures.

**Comment by coolharsh55** [comment]
Hi @dontcallmedom I have made the changes that fixed the dates and the logo is now visible. Please check if this is correct. 

(the issue with the logo was the logo placement depends on the SOTD section and the TOC sidebar added by ReSpec which assumes where the SOTD will - in DPVCG it was under another section and hence was 'hidden' behind the TOC)

**Comment by dontcallmedom** [comment]
you may want to fix the date on `examples` (July vs August)?

**Comment by coolharsh55** [comment]
Sorry - fixed the date.

**Pull request merged**
